apiVersion: apps/v1
kind: Deployment
metadata:
  name: temperature-converter
spec:
  replicas: 3
  selector:
    matchLabels:
      app: temperature-converter
  template:
    metadata:
      labels:
        app: temperature-converter
    spec:
      containers:
        - name: temperature-converter
          image: clevernvs/temperature-converter-lab:v1
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: temperature-converter
spec:
  selector:
    app: temperature-converter
  type: NodePort
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
      nodePort: 30000
